name: trump_cards
description: A super-trump card game.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.3.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  easy_localization: ^3.0.3
  flutter:
    sdk: flutter
  http: ^1.1.0
  indexed: ^0.0.8
  intl: any
  pie_chart: ^5.3.2
  shared_preferences: ^2.2.0
  url_launcher: ^6.1.12
  web_socket_channel: ^2.4.0
  file_saver: ^0.2.14
  file_picker: ^8.1.6
  google_fonts: ^6.2.1
  auto_size_text: ^3.0.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: false

  assets:
    - assets/translations/
    - assets/images/
    - assets/images/Cars/
    - assets/images/Airplanes/
    - assets/images/Rockets/
    - assets/images/animals/
    - assets/images/dinosaurs/
    - assets/images/extremeSports/
    - assets/images/megaCities/
    - assets/images/worldFootballStars/
    - assets/images/worldTennisStars/
    - assets/carddecks/
